# Nifty 200 universe — ~150 liquid large & mid caps
# Symbols use Yahoo Finance's .NS suffix for NSE
# Expand or trim this list freely; batched downloads keep yfinance load minimal

STOCKS = [
    # ── Nifty 50 (large cap backbone) ─────────────────────────────────────
    "RELIANCE.NS", "TCS.NS", "HDFCBANK.NS", "INFY.NS", "ICICIBANK.NS",
    "HINDUNILVR.NS", "SBIN.NS", "BHARTIARTL.NS", "ITC.NS", "KOTAKBANK.NS",
    "LT.NS", "AXISBANK.NS", "ASIANPAINT.NS", "MARUTI.NS", "TITAN.NS",
    "SUNPHARMA.NS", "WIPRO.NS", "ULTRACEMCO.NS", "NESTLEIND.NS", "BAJFINANCE.NS",
    "HCLTECH.NS", "POWERGRID.NS", "NTPC.NS", "ONGC.NS", "TATASTEEL.NS",
    "JSWSTEEL.NS", "TECHM.NS", "ADANIENT.NS", "BAJAJFINSV.NS", "COALINDIA.NS",
    "BRITANNIA.NS", "DIVISLAB.NS", "DRREDDY.NS", "EICHERMOT.NS", "GRASIM.NS",
    "HEROMOTOCO.NS", "HINDALCO.NS", "INDUSINDBK.NS", "M&M.NS", "SBILIFE.NS",
    "TATACONSUM.NS", "M&MFIN.NS", "CIPLA.NS", "APOLLOHOSP.NS", "HDFCLIFE.NS",
    "BPCL.NS", "ADANIPORTS.NS", "BAJAJ-AUTO.NS", "UPL.NS", "COFORGE.NS",

    # ── Nifty Next 50 / Nifty Midcap 100 ─────────────────────────────────
    "AMBUJACEM.NS", "AUROPHARMA.NS", "BANDHANBNK.NS", "BANKBARODA.NS", "BERGEPAINT.NS",
    "BIOCON.NS", "BOSCHLTD.NS", "CANBK.NS", "CHOLAFIN.NS", "COLPAL.NS",
    "CONCOR.NS", "CUMMINSIND.NS", "DABUR.NS", "DLF.NS", "DMART.NS",
    "FEDERALBNK.NS", "GAIL.NS", "GODREJCP.NS", "GODREJPROP.NS", "GRANULES.NS",
    "HAVELLS.NS", "HDFCAMC.NS", "HINDPETRO.NS", "ICICIGI.NS", "ICICIPRULI.NS",
    "IDEA.NS", "IDFCFIRSTB.NS", "IGL.NS", "INDHOTEL.NS", "INDUSTOWER.NS",
    "PAYTM.NS", "IOC.NS", "IRCTC.NS", "JINDALSTEL.NS", "JUBLFOOD.NS",
    "LALPATHLAB.NS", "LICHSGFIN.NS", "LUPIN.NS", "MARICO.NS", "UNITDSPR.NS",
    "METROPOLIS.NS", "MGL.NS", "MPHASIS.NS", "MUTHOOTFIN.NS", "NAM-INDIA.NS",
    "NAUKRI.NS", "OBEROIRLTY.NS", "PAGEIND.NS", "SUNDARMFIN.NS", "PERSISTENT.NS",
    "PETRONET.NS", "PIIND.NS", "PNB.NS", "POLYCAB.NS", "PVRINOX.NS",
    "RAJESHEXPO.NS", "RAMCOCEM.NS", "RECLTD.NS", "SAIL.NS", "SHREECEM.NS",
    "SIEMENS.NS", "SRF.NS", "STARHEALTH.NS", "SUNTV.NS", "SUPREMEIND.NS",
    "SYNGENE.NS", "TATACHEM.NS", "TATACOMM.NS", "TATAELXSI.NS", "TATAPOWER.NS",
    "TRENT.NS", "TVSMOTOR.NS", "UBL.NS", "UNIONBANK.NS", "DELHIVERY.NS",
    "VEDL.NS", "VOLTAS.NS", "ZYDUSLIFE.NS", "ACC.NS", "NYKAA.NS",

    # ── Quality Mid Caps ───────────────────────────────────────────────────
    "ABBOTINDIA.NS", "ABCAPITAL.NS", "ABFRL.NS", "ALKEM.NS", "ALOKINDS.NS",
    "ANGELONE.NS", "ASTRAL.NS", "ATUL.NS", "AWHCL.NS", "BALKRISIND.NS",
    "BATAINDIA.NS", "BAYERCROP.NS", "BRIGADE.NS", "BSOFT.NS", "CANFINHOME.NS",
    "CARBORUNIV.NS", "CASTROLIND.NS", "CDSL.NS", "CENTURYPLY.NS", "CESC.NS",
    "CHAMBLFERT.NS", "CROMPTON.NS", "CUB.NS", "DEEPAKNTR.NS", "DIXON.NS",
    "EDELWEISS.NS", "EMAMILTD.NS", "ESCORTS.NS", "EXIDEIND.NS", "FINPIPE.NS",
    "FORTIS.NS", "GLAXO.NS", "GNFC.NS", "HATSUN.NS", "HONAUT.NS",
    "IBREALEST.NS", "IFBIND.NS", "INDIACEM.NS", "INDIAMART.NS", "INDIGOPNTS.NS",
    "JKCEMENT.NS", "JKPAPER.NS", "JUBLPHARMA.NS", "KAJARIACER.NS", "KANSAINER.NS",
    "KEC.NS", "KPITTECH.NS", "KRBL.NS", "LATENTVIEW.NS", "LTTS.NS",
]

# Total: ~150 stocks
# Fetched in batches of 50 → only 3 yfinance API calls per scan run
BATCH_SIZE = 50
